### PR TITLE
fix: register shareman recovery interface in ActiveContext

### LINKED ISSUE #7243: fix: missing shareman->RegisterRecoveryInterface() in ActiveContext::Start
## Bug

`ActiveContext::Start()` registers recovery interfaces for `cl_signer` and `is_signer` but not `shareman`:

```cpp
// src/active/context.cpp — current code
cl_signer->RegisterRecoveryInterface();
is_signer->RegisterRecoveryInterface();
// shareman->RegisterRecoveryInterface(); ← MISSING
```

Without this, completed sig share sessions are only cleaned up via the 5-second `Cleanup()` interval instead of promptly via `HandleNewRecoveredSig`. The corresponding `UnregisterRecoveryInterface()` call in `Stop()` is also missing.

## Impact

- Delayed cleanup of completed sig share sessions (up to 5s instead of immediate)
- Under CI load with frozen mocktime, this manifests as flaky test failures in `feature_llmq_signing.py` and `interface_zmq_dash.py` where InstantSend locks don't arrive within expected timeouts

## Root Cause

The registration was likely dropped during the sig share refactoring that split share management into a separate `shareman` object. The `cl_signer` and `is_signer` registrations survived but `shareman` was missed.

## Fix

```cpp
// In ActiveContext::Start():
cl_signer->RegisterRecoveryInterface();
is_signer->RegisterRecoveryInterface();
+shareman->RegisterRecoveryInterface();

// In ActiveContext::Stop():
+shareman->UnregisterRecoveryInterface();
is_signer->UnregisterRecoveryInterface();
cl_signer->UnregisterRecoveryInterface();
```

## Discovery

Found during CI triage of dash#7242 (wallet deprecation backport). The fix was originally committed as `a80c46c438` on the backport branch but has been stripped out since it's unrelated to that PR's scope.

See also: dash#7233 (flaky LLMQ signing test fixes — related symptoms, different root cause).

### PR DESCRIPTION
**Pull request by thepastaclaw**
## Summary

Add missing `shareman->RegisterRecoveryInterface()` call in `ActiveContext::Start()` and corresponding `UnregisterRecoveryInterface()` in `Stop()`.

## Problem

`ActiveContext::Start()` registers recovery interfaces for `cl_signer` and `is_signer` but not `shareman`. Without this, completed sig share sessions are only cleaned up via the 5-second `Cleanup()` interval instead of promptly via `HandleNewRecoveredSig`.

Under CI load with frozen mocktime, this manifests as flaky test failures in `feature_llmq_signing.py` and `interface_zmq_dash.py` where InstantSend locks don't arrive within expected timeouts.

## Root Cause

The registration was likely dropped during the sig share refactoring that split share management into a separate `shareman` object. The `cl_signer` and `is_signer` registrations survived but `shareman` was missed.

## Fix

Two lines:

- `shareman->RegisterRecoveryInterface()` in `Start()` (after `is_signer`)
- `shareman->UnregisterRecoveryInterface()` in `Stop()` (before `is_signer`, maintaining reverse order)

## Validation

- Verified `CSigSharesManager` declares both `RegisterRecoveryInterface()` and `UnregisterRecoveryInterface()` in `src/llmq/signing_shares.h`
- Confirmed `shareman` is a `unique_ptr<CSigSharesManager>` in `ActiveContext`
- `Stop()` unregisters in reverse order of `Start()` registration (LIFO)

Closes #7243

### CODE REVIEW

**Comment by thepastaclaw** [comment]
@coderabbitai review

File: src/active/context.cpp [hunk 1]
```diff
@@ -70,6 +70,7 @@ void ActiveContext::Start(CConnman& connman, PeerManager& peerman)
     cl_signer->Start();
     cl_signer->RegisterRecoveryInterface();
     is_signer->RegisterRecoveryInterface();
+    shareman->RegisterRecoveryInterface();
```
Comment (thepastaclaw) [inline src/active/context.cpp:73]: **💬 Nitpick: Registration inconsistency: external wiring vs self-contained constructor**

`CEHFSignalsHandler` self-registers as a `CRecoveredSigsListener` in its constructor (`ehf_signals.cpp:28`) and unregisters in its destructor (`ehf_signals.cpp:33`), making it impossible to forget. In contrast, `shareman`, `cl_signer`, and `is_signer` rely on `ActiveContext::Start()`/`Stop()` to call `RegisterRecoveryInterface()` externally — which is exactly how this bug was introduced. Moving registration into each object's constructor/destructor (or its own `Start()`/`Stop()`) would prevent this class of bug. Not blocking for this PR.

<sub>source: ['claude']</sub>

**Review by thepastaclaw — COMMENTED** [review]
## Code Review

Clean 2-line wiring fix that correctly adds the missing RegisterRecoveryInterface()/UnregisterRecoveryInterface() calls for shareman in ActiveContext::Start()/Stop(). The fix matches the existing cl_signer/is_signer pattern and Stop() ordering is correctly reversed (LIFO). Both Claude and Codex confirmed the fix is correct with no blocking issues.

*Reviewed commit: 06110b90*

💬 1 nitpick(s)

**Review by UdjinM6 — APPROVED** [review]
utACK 5506d0a40aee95421d75d82ad096559d428dcf95

**Review by PastaPastaPasta — APPROVED** [review]
utACK 5506d0a40aee95421d75d82ad096559d428dcf95
